USE master;
DROP DATABASE IF EXISTS utp10;

CREATE DATABASE utp10;

USE utp10;

CREATE TABLE USERS
(
    USER_ID INT IDENTITY(1, 1) NOT NULL
    , USER_LOGIN NVARCHAR(20) NOT NULL
    , USER_PASSWORD NVARCHAR(20) NOT NULL

    , CONSTRAINT USERS_PK PRIMARY KEY(USER_ID)
);


CREATE TABLE GROUPS
(
    GROUP_ID INT IDENTITY(1, 1) NOT NULL
    , GROUP_NAME NVARCHAR(20) NOT NULL
    , GROUP_DESCRIPTION NVARCHAR(255) NOT NULL

    , CONSTRAINT GROUPS_PK PRIMARY KEY(GROUP_ID)
);


CREATE TABLE USERS_GROUPS
(
    USER_GROUP_ID INT IDENTITY(1, 1) NOT NULL
    , USER_ID INTEGER NOT NULL
    , GROUP_ID INTEGER NOT NULL

    , CONSTRAINT USERS_GROUPS_PK PRIMARY KEY(USER_GROUP_ID)
    , CONSTRAINT USERS_GROUPS_USERS_FK FOREIGN KEY(USER_ID) REFERENCES USERS(USER_ID)
    , CONSTRAINT USERS_GROUPS_GROUPS_FK FOREIGN KEY(GROUP_ID) REFERENCES GROUPS(GROUP_ID)
);